name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: events
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/events?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot && break
            echo "Waiting for MySQL..."
            sleep 2
          done
      - name: Build Backend with Tests
        run: mvn clean package -Dspring.profiles.active=test
        working-directory: ./EvenementCrud
      - name: Upload backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: EvenementCrud/target/*.jar

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./dashfront/package-lock.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install Frontend Dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./dashfront
      - name: Build Frontend
        run: ng build --configuration production
        working-directory: ./dashfront
      - name: Upload frontend dist
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dashfront/dist/**

  dockerize:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Download backend JAR
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: EvenementCrud/target

      - name: Download frontend dist
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dashfront/dist

      # Build & Push Docker Images
      - name: Build & Push Docker Images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:latest
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/cv-matching-serviceai:latest
            ${{ secrets.DOCKER_USERNAME }}/rag:latest
            ${{ secrets.DOCKER_USERNAME }}/n8n:latest
            ${{ secrets.DOCKER_USERNAME }}/scraping:latest
          build-args: |
            BACKEND_JAR=EvenementCrud/target/*.jar
          file: ./EvenementCrud/Dockerfile
          context: ./EvenementCrud

      # Pour chaque autre service, répéter le build
      - name: Build Frontend Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          file: ./dashfront/Dockerfile
          context: ./dashfront

      - name: Build AI Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cv-matching-serviceai:latest
          file: ./cv-matching-serviceAI/Dockerfile
          context: ./cv-matching-serviceAI

      - name: Build RAG Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rag:latest
          file: ./RAG/Dockerfile
          context: ./RAG

      - name: Build n8n Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/n8n:latest
          file: ./n8n/Dockerfile
          context: ./n8n

      - name: Build Scraping Docker
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/scraping:latest
          file: ./scraping/Dockerfile
          context: ./scraping

  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /chemin/vers/deploiement
            docker-compose down
            docker-compose pull
            docker-compose up -d
